### ISSUE TITLE
c2c_account_interest where are the options?

### ISSUE THREAD

**Issue by ghost** [camptocamp/c2c-rd-addons#11]
Hi

I cannot for the life of me find how to use this module..
Isnt this module for creating interest on late payments?

**Comment by Beast141** [comment]
Nevermind - figured out i have to change installable = True in the module __openerp
Not sure why this should be a manual process to change but anyway

**Comment by ferdiga** [comment]
On 2015-04-03 20:49, Beast141 wrote:

> Hi
> 
> I cannot for the life of me see the module listed in the modules list. 
> i have updated the list, i have restarted the server but to no avail 
> it doesnt get listed.. even when i clear the filter to search for it. 
> i cannot see it listed. its not my first time installing modules so i 
> am really confused why this isnt working.
> Please can someone help?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/11.
> 
> it's set "not installable" for v8, because not tested

regards
