### ISSUE TITLE
Project_task_depencendy is not working on version8

### ISSUE THREAD

**Issue by mmotahar** [camptocamp/c2c-rd-addons#13]
Hi,

Create a project with 3 tasks. 

Assign the second task as the successor of the first task. 

Below is the error message. I believe it's a small change as in version 8 it is not "state" but "stage" 

 File "/opt/odoo/custom_module/project_task_dependencies/project.py", line 169, in compute_earliest_start_successors
    if successor.state not in ('done'):
AttributeError: 'project.task' object has no attribute 'state'

**Comment by ferdiga** [comment]
On 2015-05-27 11:06, seyed-mohammad-motahar wrote:

> Hi,
> 
> Create a project with 3 tasks.
> 
> Assign the second task as the successor of the first task.
> 
> Below is the error message. I believe it's a small change as in 
> version 8 it is not "state" but "stage"
> 
> File "/opt/odoo/custom_module/project_task_dependencies/project.py", 
> line 169, in compute_earliest_start_successors
> if successor.state not in ('done'):
> AttributeError: 'project.task' object has no attribute 'state'
> 
> please make a pull request,

v8 is not supported yet

**Comment by pradeep-bhaskaran** [comment]
Just change it to -

if successor.stage_id.name not in ('Done'):

Needs to be done for all occurences of "state"

**Comment by bennals** [comment]
Hi,

Did this module get updated for v8?  It's available in the Odoo App store for v8 and I just downloaded and installed it but the error mentioned above is still occurring.

Thanks,

Bill.

**Comment by ferdiga** [comment]
it's not updated, may be for v9 or later
