### ISSUE TITLE
Cant install picking_invoice_rel

### ISSUE THREAD

**Issue by ralbear** [camptocamp/c2c-rd-addons#14]
Hi

I need to install **account_invoice_webkit** and when i try to install it this dependece module **picking_invoice_rel** i have the next issue:

[...]

``` xml
File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: stock.view_picking_out_form" while parsing /opt/odoo/addons/picking_invoice_rel/picking_view.xml:18, near
<record id="view_picking_out_invoice_rel_form" model="ir.ui.view">
      <field name="name">picking.out.invoice.rel.form</field>
      <field name="model">stock.picking</field>
      <field name="type">form</field>
      <field name="inherit_id" ref="stock.view_picking_out_form"/>
      <field name="arch" type="xml">
        <page string="Notes" position="after">
          <page string="Invoices" groups="picking_invoice_rel.group">
            <field name="invoice_ids" colspan="4" nolabel="1"/>
          </page>
        </page>
      </field>
    </record>
```

Thanks!

**Comment by ferdiga** [comment]
This module is production in v6.1 and I will be happy to commit pull requests with the correct code for v8.
my customer currently does not pay for migration.

**Comment by yvaucher** [comment]
@ralbear You might want to try by replacing `stock.view_picking_out_form` by `stock.view_picking_form` in that file `picking_invoice_rel/picking_view.xml` on line with `inherit_id`

You might get other errors to fix though as stock picking model has changed in 8.0.
