### ISSUE TITLE
Can't install c2c_real_estate

### ISSUE THREAD

**Issue by lioncodeteam** [camptocamp/c2c-rd-addons#15]
I have a tried to install c2c_real_estate to a clean database on a basic 8.0 version (after changing all dependencies to installable: true) but i got error "field 'country' does not exist". I changed 'country' to 'country_id' but i now get an error "KeyError: 'dict'" Anyone knows the reason?

**Comment by ferdiga** [comment]
On 2015-07-23 16:59, lionlocal wrote:

> I have a tried to install c2c_real_estate to a clean database on a 
> basic 8.0 version (after changing all dependencies to installable: 
> true) but i got error "field 'country' does not exist". I changed 
> 'country' to 'country_id' but i now get an error "KeyError: 'dict'" 
> Anyone knows the reason?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/15.
> 
> probably
> res_partner_address was merged into res_partner in v8 creating a lot of 
> incompatibilities with modules created for prior version

may be just comment the country field for now

regards

**Comment by jacksolutions** [comment]
just commenting out line no 109 in "chricar_top" module "'tax_res'  : fields.function(_get_tax_res, method=True, type='dict', string='Tax Result Dict',)," for the c2c_realestate app is installing fine in v8.

Thanks

**Comment by jacksolutions** [comment]
but i am not sure where it will affect in overall app..

**Comment by gemchand** [comment]
Hello;
I have tried to install c2c_real_estate in odoo 8 and it gives following error

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `country` does not exist

Error context:
View `res.partner.owner.select`
[view_id: 392, xml_id: n/a, model: res.partner, parent_id: n/a]" while parsing 

can anybody help me to install c2c_real_estate?

Thanks

**Comment by ferdiga** [comment]
On 2015-08-20 13:07, gemchand wrote:

comment out the field in xml

**Comment by gemchand** [comment]
When I am trying to install real estate addon(camptocamp/c2c-rd-addons) from github and then put in to addon folder of odoo and update module list and search real estate addon from local module . it does not show any thing related to real estate.

can anybody help me regarding this issues?

Thank You

**Comment by jacksolutions** [comment]
are you sure folder has right permission to get accessible in odoo? make sure in the addon folder you have "c2c_real_estate" folder listed, if "c2c_real_estate" is inside another folder then it wont show in update module list.

note: if you are using odoo8, it will not install this addon cause author has marked installable= false and those addons are not meant for odoo8.

Thanks

**Comment by gemchand** [comment]
Thank You jacksolution 
but problem is that there are 175 folder in real estate addon(camptocamp/c2c-rd-addons). will i have to marked installable = true in each folder?

**Comment by jacksolutions** [comment]
you will have to check the dependency of c2c_real_estate addon, which you
can check from openerp.py file, download those modules and make them
installable true.

you have to check the dependency of each folder that you download.

Thanks

On Sat, Aug 22, 2015 at 4:21 PM, gemchand notifications@github.com wrote:

> Thank You jacksolution
> but problem is that there are 175 folder in real estate
> addon(camptocamp/c2c-rd-addons). will i have to marked installable = true
> in each folder?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/camptocamp/c2c-rd-addons/issues/15#issuecomment-133676841
> .

## 

Cheers,

Jaykishan Vansadawala
(Jack Solutions)
Mob:- +91-9879455635

**Comment by gemchand** [comment]
Thank you  @jacksolutions  
I real estate module is appeared in local module and i tried to install module but it gives following error.
ProgrammingError: column "variants" does not exist

Thanks

**Comment by jacksolutions** [comment]
Most of the modules are not compatible for odoov8 and it need heavy
re-development and that is the reason they all are set to installable=false.

what you want to do let me know? may be i can help you with other modules.

Thanks

On Sat, Aug 22, 2015 at 4:57 PM, gemchand notifications@github.com wrote:

> Thank you @jacksolutions https://github.com/jacksolutions
> 
> I real estate module is appeared in local module and i tried to install
> module but it gives following error.
> ProgrammingError: column "variants" does not exist
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/camptocamp/c2c-rd-addons/issues/15#issuecomment-133678154
> .

## 

Cheers,

Jaykishan Vansadawala
(Jack Solutions)
Mob:- +91-9879455635

**Comment by gemchand** [comment]
Thank you @jacksolutions  for guiding me

can also help me to mention which folder need to marked installable = true or which folder contain dependencies of c2c_realestate?

I marked installable = true for all folder which contain **openerp**.py file?
True

**Comment by ferdiga** [comment]
On 2015-08-22 13:37, gemchand wrote:

> Thank you @jacksolutions https://github.com/jacksolutions for guiding me
> 
> can also help me to mention which folder need to marked installable = 
> true or which folder contain dependencies of c2c_realestate?
> 
> I marked installable = true for all folder which contain _openerp_.py 
> file?
> True
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/15#issuecomment-133678422.
> 
> Hi gemchand

I am the author of most of the modules in c2c_rd_addons.

odoo changes data models and view layouts from version to version and v9 
will require a complete rewrite because of incompatible API.

Please keep in mind that this is open source and we need clients to pay 
for the migration of these modules. Currently we do not plan to migrate.

Best
Ferdinand
