### ISSUE TITLE
account_cash_register_webkit

### ISSUE THREAD

**Issue by wredwan** [camptocamp/c2c-rd-addons#16]
After I installed this module, the following error massage is shown during cash register printing:
Encountered unknown tag 'running_tot'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.

except_orm: (u"Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.", (<class 'jinja2.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.",), <traceback object at 0x7f751cc621b8>))

**Comment by ferdiga** [comment]
On 2015-08-13 15:48, Walid Redwan wrote:
which odoo version - currently only 6.1 is maintained

**Comment by wredwan** [comment]
mmm 
Odoo v8

**Comment by ferdiga** [comment]
please give it a try , I merged v 6.1 into v8

**Comment by wredwan** [comment]
Ok
I test it now

**Comment by wredwan** [comment]
From Odoo Pull
:https://apps.openerp.com/apps/modules/8.0/account_cash_register_webkit/

the same error is shown after installation??

**Comment by wredwan** [comment]
I got it from github
and the new error massage is :
except_orm: (u'Webkit render!', u"'openerp.api.account.bank.statement.line object' has no attribute 'tax_id'")

**Comment by wredwan** [comment]
After I removed 
<td style="white-space:nowrap">${line.tax_id.name or ''}</td>
the report is printed but it's need some modifications 

BIG Thanks for you Mr. Ferdiga

**Comment by ferdiga** [comment]
please could you try this line instead of commenting

td style="white-space:nowrap">${'tax_id' in line._columns and line.tax_id.name or ''}</td>

**Comment by wredwan** [comment]
I don't need tax_id in my business case.
If you need my test I will do it ??

**Comment by ferdiga** [comment]
please

**Comment by wredwan** [comment]
![screenshot- domain date time](https://cloud.githubusercontent.com/assets/8244458/9292857/c2eb219c-440e-11e5-9ebd-a6621a7dab20.png)
