### ISSUE TITLE
Error while installing stock_picking_reopen on odoo v 8

### ISSUE THREAD

**Issue by n1b0r** [camptocamp/c2c-rd-addons#6]
How the stock_picking_reopen module could work on a odoo 8.0 where the model stock.journal is no more present ?

It produce an error during installation :

```
2015-03-02 09:07:50,962 21519 CRITICAL XX_1_1 openerp.service.server: Failed to initialize database `XX_1_1`.
Traceback (most recent call last):
  File "/home/YYY/sources/XX/odoo/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/YYY/sources/XX/odoo/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/YYY/sources/XX/odoo/openerp/modules/loading.py", line 357, in load_modules
    loaded_modules, update_module)
  File "/home/YYY/sources/XX/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/YYY/sources/XX/odoo/openerp/modules/loading.py", line 158, in load_module_graph
    models = registry.load(cr, package)
  File "/home/YYY/sources/XX/odoo/openerp/modules/registry.py", line 147, in load
    model = cls._build_model(self, cr)
  File "/home/YYY/sources/XX/odoo/openerp/models.py", line 566, in _build_model
    original_module = pool[name]._original_module if name in parents else cls._module
  File "/home/YYY/sources/XX/odoo/openerp/modules/registry.py", line 100, in __getitem__
    return self.models[model_name]
KeyError: 'stock.journal'
```

**Comment by ferdiga** [comment]
On 2015-03-02 13:20, Robin wrote:

> How the stock_picking_reopen module could work on a odoo 8.0 where the 
> model stock.journal is no more present ?
> 
> It produce an error during installation :
> 
> |2015-03-02 09:07:50,962 21519 CRITICAL XX_1_1 openerp.service.server: Failed to initialize database `XX_1_1`.
> Traceback (most recent call last):
>    File "/home/YYY/sources/XX/odoo/openerp/service/server.py", line 901, in preload_registries
>      registry = RegistryManager.new(dbname, update_module=update_module)
>    File "/home/YYY/sources/XX/odoo/openerp/modules/registry.py", line 324, in new
>      openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>    File "/home/YYY/sources/XX/odoo/openerp/modules/loading.py", line 357, in load_modules
>      loaded_modules, update_module)
>    File "/home/YYY/sources/XX/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
>      loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>    File "/home/YYY/sources/XX/odoo/openerp/modules/loading.py", line 158, in load_module_graph
>      models = registry.load(cr, package)
>    File "/home/YYY/sources/XX/odoo/openerp/modules/registry.py", line 147, in load
>      model = cls._build_model(self, cr)
>    File "/home/YYY/sources/XX/odoo/openerp/models.py", line 566, in _build_model
>      original_module = pool[name]._original_module if name in parents else cls._module
>    File "/home/YYY/sources/XX/odoo/openerp/modules/registry.py", line 100, in __getitem__
>      return self.models[model_name]
> KeyError: 'stock.journal'
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/6.
> 
> v8 stock related modules must still be adapted to v8 data model

greetings ferdinand

**Comment by raycarnes** [comment]
Ugh.  Why did these modules get pushed to Apps?  875 downloads and it doesn't work!
