### ISSUE TITLE
chricar_product_gtin

### ISSUE THREAD

**Issue by yelizariev** [camptocamp/c2c-rd-addons#9]
I just want to report, that in July 2014 I made some updates for  chricar_product_gtin module.
https://github.com/yelizariev/pos-addons/commits/8.0/chricar_product_gtin

If somebody is interested in those updates, feel free to use my work. I am not sure that I have time to make PR myself and work on reviews.

**Comment by ferdiga** [comment]
On 2015-03-25 15:54, Ivan Yelizariev wrote:

> I just want to report, that in July 2014 I made some updates for 
> chricar_product_gtin module.
> https://github.com/yelizariev/pos-addons/commits/8.0/chricar_product_gtin
> 
> If somebody is interested in those updates, feel free to use my work. 
> I am not sure that I have time to make PR myself and work on reviews.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/9.
> 
> Hello Ivan
> Do you agree to integrate your work (or replace the module) in the 
> c2c-rd-addons git repository ?

currently we have set most v8 modules in the git  to not installable, 
because these are not actively maintained

Best
Ferdinand

**Comment by yelizariev** [comment]
Ferdinand,
yes, I agree to publish my work in this repository. It's better than keep it at my repository, because https://apps.odoo.com doesn't show my version of the module.

**Comment by yelizariev** [comment]
Ok, I'll review code in a few days and update credentials

**Comment by ferdiga** [comment]
thanks, just a question, why does the module depend on point_of_sale
probably it should be split in gtin module and a second module which automatically is installed when point_of_sale and chricar_product_gtin is installed
what do you think

**Comment by yelizariev** [comment]
You are right. Somebody can use gtin with warehouse withount installing POS. 
Check PR, I've made changes.

**Comment by jacksolutions** [comment]
https://www.odoo.com/apps/modules/8.0/c2c_real_estate/
these modules also have installable= false when do you think it will be ready for odoo v8? i tried to install it but no luck.. do you have any installation path to install it successfully?

**Comment by ferdiga** [comment]
@jacksolutions 
may be in v9 - the client is not prepared to pay for migration every year as migration does not add any functionality and requires unnecessary training and testing. stable software should at least run for 5 years without modification.
v9 seems to bring 2 different UI and requires rewiting of all code - not sure that this will be a commercial success.
the modules are developed for 6.1

**Comment by jacksolutions** [comment]
yes i agree. is there any use case of real estate management? any documentation? screenshot? list of functionalities that is being implemented or supported in that version? any migration path to convert from 6.1 to 8? i am myself a developer if you help me in those , i can code it for v8 and send it back to you? 

what do you think regarding v9 for 2 different UI? by 2 different UI there will be a lot of complication for both odoo saas as well as developer like us.. is there any chance of new community from v9 onwards same as openerp created from tryton? cause convert licences and 2 different UI seems to be fishy... 

also i have heard that they are developing mobile client in phonegap now? is it true? will it be available for public? source code? cause at the moment using their mobile application for customer is risk of loosing the customer cause they have there branding in there? any other way?

**Comment by ferdiga** [comment]
it's a statistical tool right now to keep track of tenants, paid rents
, budgeted repairs, see empty tops over multiple sites 
![real estate top](https://cloud.githubusercontent.com/assets/6248560/8761084/30a6066c-2d3e-11e5-88fc-86784e08216f.png)

**Comment by jacksolutions** [comment]
seems to be good so far, not what i actually wanted but the screenshot has given me another idea.. thank you for the screenshot.

now what is the upgrade path for the modules? if you shed some lights i can start working on that line?

**Comment by ferdiga** [comment]
install or upgrade ?
clone 
for installation set installable=true and then
trial and error ;-(
use c2c_real_estate module which tries to install all needed modules

```
'depends': [
```

"chricar_top"
,"chricar_tenant"
,"chricar_invoice"
,"chricar_room"
,"chricar_equipment"]

**Comment by jacksolutions** [comment]
okay will do.. thank you camptocamp, you are guys rock!

thanks

**Comment by jacksolutions** [comment]
i am seeing lots of modules under you on apps store on odoo, how many years of efforts is that? do you offer your own SAAS or you forward customers to odoo saas? what kind of products you are selling based on odoo? any business tips :) which i can do here in india in my small town?

**Comment by ferdiga** [comment]
SAAS is not flexible enough and does not support Austrian requirements. Most modules add functionality required in Austria and improved user experience - especially reverting wrong data entries, budgeting etc. Many basic things we expected to be covered in the openerp/odoo base modules.

**Comment by jacksolutions** [comment]
just commenting out line no 109 in "chricar_top" module "'tax_res' : fields.function(_get_tax_res, method=True, type='dict', string='Tax Result Dict',)," for the c2c_realestate app is installing fine in v8.
but i am not sure where it will affect in overall app..

now where can i get the documentation for overall app? how to use it etc etc? can you please PM me if you have? that would be appreciated.. also i will dig further to fully supported it to v8 if i get actual documentation of the app.. 

i am not sure at the moment what this module achieve in real estate management industry? can you please explain me in detail?

**Comment by ferdiga** [comment]
On 2015-07-29 07:51, jacksolutions wrote:

> just commenting out line no 109 in "chricar_top" module "'tax_res' : 
> fields.function(_get_tax_res, method=True, type='dict', string='Tax 
> Result Dict',)," for the c2c_realestate app is installing fine in v8.
> but i am not sure where it will affect in overall app..
> 
> now where can i get the documentation for overall app? how to use it 
> etc etc? can you please PM me if you have? that would be appreciated.. 
> also i will dig further to fully supported it to v8 if i get actual 
> documentation of the app..
> 
> i am not sure at the moment what this module achieve in real estate 
> management industry? can you please explain me in detail?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/9#issuecomment-125850391.
> 
> the modules allows to keep an evidence of all tops in different 
> buildings as well as the history of tenanats. most important is the 
> ability to define current rents and possible rents to calculate the upside.

the deactivated tax_res allows to enter and print the tax results of the 
past years in an excel like report

**Comment by jacksolutions** [comment]
what do you mean by "tops" in realestate though.. ? i am seeing lots of options like blueprints, equipments, etc etc? what are the use of them?

**Comment by jacksolutions** [comment]
http://awesomescreenshot.com/0a453u16ed

As i am not sure you have any documentation for how to use this software i think i have to ask many questions to understand how it actually works? :( sorry for that!

**Comment by ferdiga** [comment]
On 2015-07-29 09:23, jacksolutions wrote:

> http://awesomescreenshot.com/0a453u16ed
> 
> As i am not sure you have any documentation for how to use this 
> software i think i have to ask many questions to understand how it 
> actually works? :( sorry for that!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/camptocamp/c2c-rd-addons/issues/9#issuecomment-125868333.
> 
> you are right  - there is no explicit documentation
> the forms are self explaining. at least for our users

regards
